build: update cathy to v2 version rewritten in deno (#141)
## Related GitHub Issues
<!-- Link to any related GitHub issues that this pull request addresses
or closes. -->

## Problem
<!-- A clear description of the problem that this pull request is
solving. -->

I have been seeing weird "Uncaught (in promise) Error: socket hang up"
(with no stacktrace) errors when running decaf. I only get it during
test mode. All of the decaf code runs successfully, including teardown
of the git clone and everything.

```
 $> deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases get
Latest git tag on the current branch is: 0.5.1
latest release found: 0.5.1 (0.5.1)
commit matching release found: fix: attach readme to the deno module. because, you know, you need docs (#8) (44b0c3d0915014aa925a2c5fbe91329278f6abf2)
Warning: ⚠️ Verification failed, but that could be expected in test mode. The latest release after deployment is 0.5.1, but expected 0.6.0. This could indicate a problem with the deployment process.
🎉 Congratulations! The deployment process has completed. Bye-bye 👋!
error: Uncaught (in promise) Error: socket hang up
    at connResetException (ext:deno_node/internal/errors.ts:1969:14)
    at node:http:512:30
Error: Process completed with exit code 1.
```

> above is the actual error. 

## Solution
<!-- Describe the approach you took to solve the problem and the changes
made in this pull request. -->

Not totally sure yet, but I do wonder if it's due to cathy. It might not
be, but cathy only runs on test mode so it makes me wonder. So, updating
it to the latest version to see if it helps.

## Testing
<!-- Choose one of the below options for how you tested the code change.
Include any specific setup or instructions for testing. -->
- [ ] Added automated tests. 
- [ ] Manually tested. If you check this box, provide instructions for
others to test, too.

## Notes for reviewers 
<!-- If there is any additional information you would like to share with
the person reviewing this pull request, please provide it here. -->