build: compile binary with deno 2.2 because potential bug found in 2.3
The CI server upgraded to v2.3.1 today over 2.2. The compiled binary hit a runtime exception and so as a fix, I am locking to 2.2 and reporting the bug.

Error I got:

error: Uncaught (in promise) NotCapable: Requires env access to "NODE_V8_COVERAGE", specify the required permissions during compilation using `deno compile --allow-env`
if (global.FinalizationRegistry && !process.env.NODE_V8_COVERAGE) {
                                                ^
    at Object.getEnv [as get] (ext:deno_os/30_os.js:124:10)
    at denoEnvGet (ext:deno_node/_process/process.ts:27:21)
    at Object.get (ext:deno_node/_process/process.ts:44:22)
    at Object.<anonymous> (file:///tmp/deno-compile-deployer/.deno_compile_node_modules/localhost/undici/5.28.4/lib/core/connect.js:18:49)
    at Object.<anonymous> (file:///tmp/deno-compile-deployer/.deno_compile_node_modules/localhost/undici/5.28.4/lib/core/connect.js:191:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Module._load (node:module:534:12)